style = "sciml"
format_markdown = true
format_docstrings = true
indent = 3
import_to_using = true
remove_extra_newlines = true
long_to_short_function_def = true
indent_submodule = true
surround_whereop_typeparameters = false
