style = "sciml"
format_markdown = true
format_docstrings = true
indent = 3
for_in_replacement = \"∈\"
import_to_using = true
remove_extra_newlines = true
long_to_short_function_def = true
normalize_line_endings = \"unix\"
indent_submodule = true
surround_whereop_typeparameters = false
