name = "TestParticleMakie"
uuid = "815e1cc4-5742-45dc-845d-1cec70514f1a"
authors = ["TCLiuu <liutc@mail.nankai.edu.cn>"]
version = "0.1.3"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
Makie = "0.17, 0.18, 0.19"
julia = "1.6"
SciMLBase = "1, 2"