name: Format suggestions
on:
  pull_request:
    # this argument is not required if you don't use the `suggestion-label` input
    types: [ opened, reopened, synchronize, labeled, unlabeled ]

    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'examples/**'
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/julia-format@v4
        with:
          version: '1' # version 2 is also available (default: '1')
          suggestion-label: 'format-suggest' # leave this unset or empty to show suggestions for all PRs